# Generated by Django 4.2.3 on 2023-07-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=120)),
                ('short_title', models.CharField(max_length=120)),
                ('logo', models.ImageField(upload_to='')),
                ('contact_number', models.CharField(max_length=120)),
                ('address_1', models.CharField(max_length=120)),
                ('address_2', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('zip_code', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(max_length=120)),
            ],
        ),
    ]
