# Generated by Django 4.2.3 on 2023-07-29 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=120)),
                ('client_short_name', models.CharField(max_length=120)),
                ('contact_manager', models.CharField(max_length=120)),
                ('contact_mail', models.EmailField(max_length=254)),
                ('contact_phone_number', models.CharField(max_length=120)),
                ('contact_address', models.CharField(max_length=120)),
                ('status', models.CharField(max_length=120)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.company')),
            ],
        ),
    ]
