# Generated by Django 4.2.3 on 2023-07-29 15:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_clients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=120)),
                ('project_short_name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=120)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.clients')),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=120)),
                ('team_short_name', models.CharField(max_length=120)),
                ('team_manager', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=120)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.clients')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.company')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.projects')),
            ],
        ),
    ]
